version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    timezone: America/Chicago
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: com.diffplug.spotless
    versions:
    - 5.10.0
    - 5.10.1
    - 5.10.2
    - 5.11.0
    - 5.11.1
    - 5.12.0
    - 5.12.1
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.1
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.1
  - dependency-name: org.junit.jupiter:junit-jupiter-params
    versions:
    - 5.7.1
  - dependency-name: io.netty:netty-handler
    versions:
    - 4.1.58.Final
  - dependency-name: io.netty:netty-transport
    versions:
    - 4.1.58.Final
  - dependency-name: de.jjohannes.extra-java-module-info
    versions:
    - "0.5"
  - dependency-name: org.fusesource.jansi:jansi
    versions:
    - 2.2.0
  - dependency-name: io.netty:netty-codec-dns
    versions:
    - 4.1.58.Final
  - dependency-name: io.netty:netty-resolver-dns
    versions:
    - 4.1.58.Final
  - dependency-name: io.netty:netty-common
    versions:
    - 4.1.58.Final
  - dependency-name: io.netty:netty-codec
    versions:
    - 4.1.58.Final
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.1
