sudo: false

matrix:
  include:
    - language: java
      name: Java 13 Linux
      os: linux
      jdk: openjdk13
      script:
        - ./gradlew test --console=plain

    - language: java
      name: Java 13 macOS
      os: osx
      jdk: openjdk13
      script:
        - ./gradlew test --console=plain

    - language: swift
      name: Lockstone iOS
      os: osx
      osx_image: xcode11.2
      script:
        - ./gradlew :com.sandpolis.client.lockstone:build -PLOCKSTONE=true --console=plain
      podfile: com.sandpolis.client.lockstone/Podfile
      cache:
        cocoapods: true
      addons:
        homebrew:
          packages:
          - protobuf
          - swift-protobuf
