sudo: false

matrix:
  include:
    - language: java
      name: Java 12 Linux
      os: linux
      jdk: openjdk12
      script:
        - ./gradlew test -PPLUGINS_DEPLOY=false --console=plain

    - language: java
      name: Java 12 macOS
      os: osx
      jdk: openjdk12
      script:
        - ./gradlew test -PPLUGINS_DEPLOY=false --console=plain

    #allow_failures:
    #- language: swift
    #  name: Lockstone iOS
    #  os: osx
    #  osx_image: xcode10.3
    #  script:
    #    - ./gradlew :com.sandpolis.viewer.lockstone:build -PPLUGINS_DEPLOY=false -PLOCKSTONE=true --console=plain
    #  cache:
    #    cocoapods: true
