version: '{build}'

image: Visual Studio 2019

branches:
  only:
    - master

skip_tags: true

environment:
  TERM: dumb
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk12

init:
  - git config --global --unset core.autocrlf

install:
  - gradlew --version

build_script:
  - gradlew assemble --console=plain

test_script:
  - gradlew test --console=plain
