version: '{build}'

image: Visual Studio 2015

branches:
  only:
    - master

skip_tags: true

environment:
  TERM: dumb
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk11

init:
  - git config --global --unset core.autocrlf
  - set GRADLE_OPTS="-Dorg.gradle.daemon=false"

install:
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - echo %PATH%
  - java -version
  - gradlew.bat --version

build_script:
  - gradlew assemble -PPLUGINS_DEPLOY=false

test_script:
  - gradlew test -PPLUGINS_DEPLOY=false
